-- MySQL Script generated by MySQL Workbench
-- 01/02/15 11:39:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `folder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `folder` (
  `idfolder` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(60) NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `active` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idfolder`),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `picture` (
  `idpicture` INT NOT NULL AUTO_INCREMENT,
  `idfolder` INT NOT NULL,
  `name` VARCHAR(140) NULL,
  `link` VARCHAR(100) NOT NULL,
  `ordered` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idpicture`),
  INDEX `fk_folder_idfolder_idx` (`idfolder` ASC),
  CONSTRAINT `fk_folder_idfolder`
    FOREIGN KEY (`idfolder`)
    REFERENCES `folder` (`idfolder`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
